### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by bkr32** [binkybear/rock3tman#1]
i get the following syntax error

rocketman.sh: 35: rocketman.sh: [[: not found
rocketman.sh: 41: rocketman.sh: [[: not found
rocketman.sh: 78: rocketman.sh: Syntax error: "(" unexpected (expecting "}")

**Comment by binkybear** [comment]
Can you try again?  I'm still getting some routing issue.  VPN works fine...just not as a reverse yet.

**Comment by bkr32** [comment]
rocketman.sh: 37: rocketman.sh: [[: not found
rocketman.sh: 43: rocketman.sh: [[: not found
rocketman.sh: 80: rocketman.sh: Syntax error: "(" unexpected (expecting "}")

although i launch it using sh rocketman.sh

**Comment by binkybear** [comment]
I don't believe you are using bash in that case.  You should just launch with ./rocketman.sh since it has the !#/bin/bash

**Comment by bkr32** [comment]
using ./rocketman.sh produces permission denied error

**Comment by binkybear** [comment]
chmod +x rocketman.sh

**Comment by bkr32** [comment]
working great, 
if we choose no on get external IP does it pick server ip from the sh file?
i'd like to use my subdomain name instead of external IP

**Comment by binkybear** [comment]
Closing this issue since syntax is OK but I added option to ask for ip/domain.
